### ISSUE TITLE
Value of type 'VNFaceLandmarkRegion2D' has no member 'point'

### ISSUE THREAD

**Issue by bharath989** [mattlawer/FaceLandmarksDetection#1]
/Users/apple/Pictures/DRIVE X/Face Filters/FaceLandmarksDetection-master/DetectFaceLandmarks/FaceLandmarksDetector.swift:70:29: Value of type 'VNFaceLandmarkRegion2D' has no member 'point'

![screen shot 2018-01-03 at 11 28 30 am](https://user-images.githubusercontent.com/18612249/34510363-454054d2-f079-11e7-8694-97b7005e8ed2.png)

**Comment by mattlawer** [comment]
Thanks, the point(at:) method was deprecated by Apple.
I just fixed it in commit [87f29d7](https://github.com/mattlawer/FaceLandmarksDetection/commit/87f29d7266ec1b336ab78c62b22521e5ed28788e).

Have a good day! (And happy new year BTW 😁)
