### ISSUE TITLE
what scale used to set the green boarder

### ISSUE THREAD

**Issue by razan1994alali** [mattlawer/FaceLandmarksDetection#2]
I'm trying to add a view over the face detected, but I'm unable to find the scale used to add the green boarder over the detected face. for more explanation here is what i tried to do:

in FaceLandmarksDetector:

`      context.setStrokeColor(UIColor.green.cgColor)
        context.addRect(CGRect(x: boundingRect.origin.x * source.size.width, y:boundingRect.origin.y * source.size.height, width: rectWidth, height: rectHeight))
        context.drawPath(using: CGPathDrawingMode.stroke)
		
	**let overView = CGRect(x: boundingRect.origin.x * source.size.width, y: boundingRect.origin.y * source.size.height, width: rectWidth, height: rectHeight)
	setOverView(with: overView, in: view)**
		
		
        //draw overlay
        context.setLineWidth(1.0)`

the code i added gave this result:

![img_6941](https://user-images.githubusercontent.com/20578884/35212569-449325c0-ff63-11e7-8786-2d95466d6e6f.PNG)

any help for this issue?
Thank you in advance.

**Comment by mattlawer** [comment]
Hi, the `boundingRect` value represents the rect inside the `source` UIImage.
When drawing on the image we just need to multiply the `boundingRect` attributes by the `source` width (for `x` & `width`) or height (for `y` & `height`).
The image drawn is rendered by filling the UIImageView frame, the `source` image size is different from the UIImageView frame size.
If you want to add a UIView on top of the detected face you also have to apply the scale applied to the image when filling the UIImageView frame.
It could be done by multiplying every attributes of the rect by (`imageView.frame.size.width/source.size.width`) or (`imageView.frame.size.height/source.size.height`) depending the size of your imageView vs the size of the source image.

Hope this will help you, have a good day !
